linters-settings:
  dupl:
    threshold: 100
  lll:
    line-length: 80
  varnamelen:
    ignore-names:
      - v
      - ok

linters:
  enable-all: true
  disable:
    - exhaustruct
    - depguard
    - thelper

issues:
  exclude-dirs:
    - testdata
  exclude-rules:
    - path: lint_test
      linters:
        - varnamelen
        - wrapcheck
    - linters:
        - lll
      source: "^(?: |\t)*// "
    - linters:
        - lll
      source: "[`\"'].*[`\"']"
    - linters:
        - godot
        - lll
      source: "// ?TODO "
